services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    environment:
      - FLASK_DEBUG=false
      - SECRET_KEY=h4ufhuzehphduhs144fhuehôùsgdfpieh44vsdph5
    expose:
      - "8000"
    volumes:
      # On lie le dossier local 'app/static' au volume Docker
      - ./app/static:/app/app/static 
      - static_content:/app/app/static
    deploy:
      replicas: 3

  proxy:
    image: nginx:latest
    container_name: g_twitter_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Nginx va lire dans ce même volume
      - static_content:/usr/share/nginx/html/static:ro 
    depends_on:
      - app
    restart: always

volumes:
  static_content: